version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    volumes:
      - .:/src/app
      - /src/app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgres://todouser:todopass@postgres:5432/tododb
    ports:
      - '3000:3000'

  postgres:
    container_name: pg_container
    image: postgres:12.9
    restart: always
    environment:
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
      POSTGRES_DB: tododb
    ports:
      - '5432:5432'
